version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.9.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 19.03.14
      - run: docker build .
